=== diegomarty00/sew-25-26/Baleares-Desktop/xml/circuito.dtd
<!ELEMENT circuito  (datos, tramos, resultados)>
        <!ELEMENT datos (longitudCircuito, anchura,
                fechaCarrera, horaCarreraEsp, vueltas, 
                localidad, pais, patrocinador, 
                referencias, multimedia, 
                coordenadasCircuito)>

        <!ELEMENT longitudCircuito (#PCDATA)>
        <!ELEMENT anchura (#PCDATA)>
        <!ELEMENT fechaCarrera (#PCDATA)>
        <!ELEMENT horaCarreraEsp (#PCDATA)>
        <!ELEMENT vueltas (#PCDATA)>
        <!ELEMENT localidad (#PCDATA)>
        <!ELEMENT pais (#PCDATA)>
        <!ELEMENT patrocinador (#PCDATA)>
        <!ELEMENT referencias (referencia+)>
        <!ELEMENT referencia (#PCDATA)>
        <!ELEMENT multimedia (foto+, video+)>
        <!ELEMENT foto (#PCDATA)>
        <!ELEMENT video (#PCDATA)>
        <!ELEMENT coordenadasCircuito (longitud, latitud, altitud)>

        <!ELEMENT tramos (tramo*)>
        <!ELEMENT tramo (distancia, coordenadasTramoFin, sector)>
        <!ELEMENT distancia (#PCDATA)>
        <!ELEMENT coordenadasTramoFin (longitud, latitud, altitud)>
        <!ELEMENT sector (#PCDATA)>


        <!ELEMENT longitud (#PCDATA)>
        <!ELEMENT latitud (#PCDATA)>
        <!ELEMENT altitud (#PCDATA)>

        <!ELEMENT resultados (ganador, tiempoGP, clasificacion)>
        <!ELEMENT ganador (#PCDATA)>
        <!ELEMENT tiempoGP (#PCDATA)>
        <!ELEMENT clasificacion (piloto*)>
        <!ELEMENT piloto (#PCDATA)>

        <!ATTLIST circuito
                nombreCircuito CDATA #REQUIRED>
        <!ATTLIST tramo
                numeroTramo CDATA #REQUIRED>
        <!ATTLIST piloto
                posicion CDATA #REQUIRED
                puntos CDATA #REQUIRED>
        <!ATTLIST tiempoGP
                unidad CDATA #REQUIRED>
        <!ATTLIST longitudCircuito
                unidad  CDATA #REQUIRED>
        <!ATTLIST anchura 
                unidad ID #REQUIRED>
        <!ATTLIST distancia
                unidad  CDATA #REQUIRED>
        <!ATTLIST longitud
                unidad  CDATA #REQUIRED>
        <!ATTLIST latitud
                unidad  CDATA #REQUIRED>
        <!ATTLIST altitud
                unidad  CDATA #REQUIRED>

=== diegomarty00/sew-25-26/Baleares-Desktop/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">


<circuito nombreCircuito="Automotodrom Brno">
    <datos>
        <longitudCircuito unidad="metros">5403</longitudCircuito>
        <anchura unidad="metros">15</anchura>
        <fechaCarrera>7 de Julio</fechaCarrera>
        <horaCarreraEsp>15:00</horaCarreraEsp>
        <vueltas>21</vueltas>
        <localidad>Brno</localidad>
        <pais>República Checa</pais>
        <patrocinador>Tissot</patrocinador>
        <referencias>
            <referencia>https://www.motogpbrno.com/es</referencia>
            <referencia>https://www.automotodrombrno.cz/en/moto-gp/</referencia>
            <referencia>https://en.wikipedia.org/wiki/Brno_Circuit</referencia>
        </referencias>
        <multimedia>
            <foto>https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Jeddah_Street_Circuit_2021.svg/1024px-Jeddah_Street_Circuit_2021.svg.png</foto>
            <video>https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Jeddah_Street_Circuit_2021.svg/1024px-Jeddah_Street_Circuit_2021.svg.png</video>
        </multimedia>
        <coordenadasCircuito>
            <longitud unidad="grados">49.203574</longitud>
            <latitud unidad="grados">16.442826</latitud>
            <altitud unidad="metros">436</altitud>
        </coordenadasCircuito>
    </datos>
    <tramos>
        <tramo numeroTramo="1">
            <distancia unidad="metros">410</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.205726</longitud>
                <latitud unidad="grados">16.439388</latitud>
                <altitud unidad="metros">432</altitud>
            </coordenadasTramoFin>
            <sector>1</sector>
        </tramo>
        <tramo numeroTramo="2">
            <distancia unidad="metros">235</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.205824</longitud>
                <latitud unidad="grados">16.442209</latitud>
                <altitud unidad="metros">435</altitud>
            </coordenadasTramoFin>
            <sector>1</sector>
        </tramo>
        <tramo numeroTramo="3">
            <distancia unidad="metros">605</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.206241</longitud>
                <latitud unidad="grados">16.450653</latitud>
                <altitud unidad="metros">441</altitud>
            </coordenadasTramoFin>
            <sector>1</sector>
        </tramo>
        <tramo numeroTramo="4">
            <distancia unidad="metros">225</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.208078</longitud>
                <latitud unidad="grados">16.450101</latitud>
                <altitud unidad="metros">445</altitud>
            </coordenadasTramoFin>
            <sector>2</sector>
        </tramo>
        <tramo numeroTramo="5">
            <distancia unidad="metros">555</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.209139</longitud>
                <latitud unidad="grados">16.457579</latitud>
                <altitud unidad="metros">424</altitud>
            </coordenadasTramoFin>
            <sector>2</sector>
        </tramo>
        <tramo numeroTramo="6">
            <distancia unidad="metros">190</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.207598</longitud>
                <latitud unidad="grados">16.457385</latitud>
                <altitud unidad="metros">414</altitud>
            </coordenadasTramoFin>
            <sector>2</sector>
        </tramo>
        <tramo numeroTramo="7">
            <distancia unidad="metros">200</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.207111</longitud>
                <latitud unidad="grados">16.455100</latitud>
                <altitud unidad="metros">421</altitud>
            </coordenadasTramoFin>
            <sector>2</sector>
        </tramo>
        <tramo numeroTramo="8">
            <distancia unidad="metros">305</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.205670</longitud>
                <latitud unidad="grados">16.458330</latitud>
                <altitud unidad="metros">415</altitud>
            </coordenadasTramoFin>
            <sector>2</sector>
        </tramo>
        <tramo numeroTramo="9">
            <distancia unidad="metros">165</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.206739</longitud>
                <latitud unidad="grados">16.459526</latitud>
                <altitud unidad="metros">404</altitud>
            </coordenadasTramoFin>
            <sector>3</sector>
        </tramo>
        <tramo numeroTramo="10">
            <distancia unidad="metros">705</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.201839</longitud>
                <latitud unidad="grados">16.464247</latitud>
                <altitud unidad="metros">381</altitud>
            </coordenadasTramoFin>
            <sector>3</sector>
        </tramo>
        <tramo numeroTramo="11">
            <distancia unidad="metros">355</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.202922</longitud>
                <latitud unidad="grados">16.459730</latitud>
                <altitud unidad="metros">389</altitud>
            </coordenadasTramoFin>
            <sector>3</sector>
        </tramo>
        <tramo numeroTramo="12">
            <distancia unidad="metros">145</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.201952</longitud>
                <latitud unidad="grados">16.458753</latitud>
                <altitud unidad="metros">405</altitud>
            </coordenadasTramoFin>
            <sector>3</sector>
        </tramo>
        <tramo numeroTramo="13">
            <distancia unidad="metros">605</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.203520</longitud>
                <latitud unidad="grados">16.450712</latitud>
                <altitud unidad="metros">432</altitud>
            </coordenadasTramoFin>
            <sector>4</sector>
        </tramo>
        <tramo numeroTramo="14">
            <distancia unidad="metros">200</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.202060</longitud>
                <latitud unidad="grados">16.449312</latitud>
                <altitud unidad="metros">440</altitud>
            </coordenadasTramoFin>
            <sector>4</sector>
        </tramo>
        <tramo numeroTramo="0">
            <distancia unidad="metros">503</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.203574</longitud>
                <latitud unidad="grados">16.442826</latitud>
                <altitud unidad="metros">436</altitud>
            </coordenadasTramoFin>
            <sector>4</sector>
        </tramo>
    </tramos>
    <resultados>
        <ganador>M. Marquez</ganador>
        <tiempoGP unidad="minutos">40,04.628</tiempoGP>
        <clasificacion>
            <piloto posicion="1" puntos="545">Marc Márquez</piloto>
            <piloto posicion="2" puntos="362">Álex Márquez</piloto>
            <piloto posicion="3" puntos="274">Pecco Bagnaia</piloto>
        </clasificacion>
    </resultados>
</circuito>
