=== diegomarty00/sew-25-26/Baleares-Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.uniovi.es"
  xmlns="http://www.uniovi.es"
  elementFormDefault="qualified">
  <xs:element name="circuito">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="datos" />
        <xs:element ref="tramos" />
        <xs:element ref="resultados" />
      </xs:sequence>
      <xs:attribute name="nombreCircuito" type="xs:ID" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="datos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="longitudCircuito" />
        <xs:element ref="anchura" />
        <xs:element ref="fechaCarrera" />
        <xs:element ref="horaCarreraEsp" />
        <xs:element ref="vueltas" />
        <xs:element ref="localidad" />
        <xs:element ref="pais" />
        <xs:element ref="patrocinador" />
        <xs:element ref="referencias" />
        <xs:element ref="multimedia" />
        <xs:element ref="coordenadasCircuito" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="longitudCircuito">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="unidad" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="anchura">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="unidad" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="fechaCarrera" type="xs:date" />
  <xs:element name="horaCarreraEsp" type="xs:time" />
  <xs:element name="vueltas">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="1" />
        <xs:maxInclusive value="100" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="localidad" type="xs:string" />
  <xs:element name="pais" type="xs:string" />
  <xs:element name="patrocinador" type="xs:string" />
  <xs:element name="referencias">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="referencia" type="xs:string" />
  <xs:element name="multimedia">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="5" ref="foto" />
        <xs:element minOccurs="1" maxOccurs="3" ref="video" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="foto" type="xs:string" />
  <xs:element name="video" type="xs:string" />
  <xs:element name="coordenadasCircuito">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="longitud" />
        <xs:element ref="latitud" />
        <xs:element ref="altitud" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tramos">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="3" maxOccurs="unbounded" ref="tramo" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tramo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="distancia" />
        <xs:element ref="coordenadasTramoFin" />
        <xs:element ref="sector" />
      </xs:sequence>
      <xs:attribute name="numeroTramo" type="xs:integer" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="distancia">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="unidad" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="coordenadasTramoFin">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="longitud" />
        <xs:element ref="latitud" />
        <xs:element ref="altitud" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="sector" type="xs:integer" />
  
  <xs:simpleType name="LatitudType">
    <xs:restriction base="xs:double">
      <xs:minInclusive value="-90"/>
      <xs:maxInclusive value="90"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="LongitudType">
    <xs:restriction base="xs:double">
      <xs:minInclusive value="-180"/>
      <xs:maxInclusive value="180"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="AltitudType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="5000"/>
    </xs:restriction>
  </xs:simpleType> 

  <xs:element name="longitud">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="LongitudType">
          <xs:attribute name="unidad" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="latitud">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="LatitudType">
          <xs:attribute name="unidad" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="altitud">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="AltitudType">
          <xs:attribute name="unidad" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="resultados">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ganador" />
        <xs:element ref="tiempoGP" />
        <xs:element ref="clasificacion" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ganador" type="xs:string" />
  <xs:element name="tiempoGP">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:duration">
          <xs:attribute name="unidad" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="clasificacion">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="3" maxOccurs="3" ref="piloto" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="piloto">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="posicion" type="xs:integer" use="required" />
          <xs:attribute name="puntos" type="xs:integer" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== diegomarty00/sew-25-26/Baleares-Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>

<circuito nombreCircuito="Automotodrom-Brno" 
xmlns="http://www.uniovi.es" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.uniovi.es circuito.xsd">
    <datos>
        <longitudCircuito unidad="metros">5403</longitudCircuito>
        <anchura unidad="metros">15</anchura>
        <fechaCarrera>2025-07-07</fechaCarrera>
        <horaCarreraEsp>15:00:00</horaCarreraEsp>
        <vueltas>21</vueltas>
        <localidad>Brno</localidad>
        <pais>República Checa</pais>
        <patrocinador>Tissot</patrocinador>
        <referencias>
            <referencia>https://www.motogpbrno.com/es</referencia>
            <referencia>https://www.automotodrombrno.cz/en/moto-gp/</referencia>
            <referencia>https://en.wikipedia.org/wiki/Brno_Circuit</referencia>
        </referencias>
        <multimedia>
            <foto>multimedia/imagenes/Automotodrom-Brno-plano.jpg</foto>
            <video>multimedia/videos/franco-morbidelli-vuelve-a-los-entrenamientos-motogp-Peq.mp4</video>
        </multimedia>
        <coordenadasCircuito>
            <longitud unidad="grados">49.203574</longitud>
            <latitud unidad="grados">16.442826</latitud>
            <altitud unidad="metros">436</altitud>
        </coordenadasCircuito>
    </datos>
    <tramos>
        <tramo numeroTramo="1">
            <distancia unidad="metros">410</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.205726</longitud>
                <latitud unidad="grados">16.439388</latitud>
                <altitud unidad="metros">432</altitud>
            </coordenadasTramoFin>
            <sector>1</sector>
        </tramo>
        <tramo numeroTramo="2">
            <distancia unidad="metros">235</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.205824</longitud>
                <latitud unidad="grados">16.442209</latitud>
                <altitud unidad="metros">435</altitud>
            </coordenadasTramoFin>
            <sector>1</sector>
        </tramo>
        <tramo numeroTramo="3">
            <distancia unidad="metros">605</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.206241</longitud>
                <latitud unidad="grados">16.450653</latitud>
                <altitud unidad="metros">441</altitud>
            </coordenadasTramoFin>
            <sector>1</sector>
        </tramo>
        <tramo numeroTramo="4">
            <distancia unidad="metros">225</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.208078</longitud>
                <latitud unidad="grados">16.450101</latitud>
                <altitud unidad="metros">445</altitud>
            </coordenadasTramoFin>
            <sector>2</sector>
        </tramo>
        <tramo numeroTramo="5">
            <distancia unidad="metros">555</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.209139</longitud>
                <latitud unidad="grados">16.457579</latitud>
                <altitud unidad="metros">424</altitud>
            </coordenadasTramoFin>
            <sector>2</sector>
        </tramo>
        <tramo numeroTramo="6">
            <distancia unidad="metros">190</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.207598</longitud>
                <latitud unidad="grados">16.457385</latitud>
                <altitud unidad="metros">414</altitud>
            </coordenadasTramoFin>
            <sector>2</sector>
        </tramo>
        <tramo numeroTramo="7">
            <distancia unidad="metros">200</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.207111</longitud>
                <latitud unidad="grados">16.455100</latitud>
                <altitud unidad="metros">421</altitud>
            </coordenadasTramoFin>
            <sector>2</sector>
        </tramo>
        <tramo numeroTramo="8">
            <distancia unidad="metros">305</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.205670</longitud>
                <latitud unidad="grados">16.458330</latitud>
                <altitud unidad="metros">415</altitud>
            </coordenadasTramoFin>
            <sector>2</sector>
        </tramo>
        <tramo numeroTramo="9">
            <distancia unidad="metros">165</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.206739</longitud>
                <latitud unidad="grados">16.459526</latitud>
                <altitud unidad="metros">404</altitud>
            </coordenadasTramoFin>
            <sector>3</sector>
        </tramo>
        <tramo numeroTramo="10">
            <distancia unidad="metros">705</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.201839</longitud>
                <latitud unidad="grados">16.464247</latitud>
                <altitud unidad="metros">381</altitud>
            </coordenadasTramoFin>
            <sector>3</sector>
        </tramo>
        <tramo numeroTramo="11">
            <distancia unidad="metros">355</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.202922</longitud>
                <latitud unidad="grados">16.459730</latitud>
                <altitud unidad="metros">389</altitud>
            </coordenadasTramoFin>
            <sector>3</sector>
        </tramo>
        <tramo numeroTramo="12">
            <distancia unidad="metros">145</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.201952</longitud>
                <latitud unidad="grados">16.458753</latitud>
                <altitud unidad="metros">405</altitud>
            </coordenadasTramoFin>
            <sector>3</sector>
        </tramo>
        <tramo numeroTramo="13">
            <distancia unidad="metros">605</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.203520</longitud>
                <latitud unidad="grados">16.450712</latitud>
                <altitud unidad="metros">432</altitud>
            </coordenadasTramoFin>
            <sector>4</sector>
        </tramo>
        <tramo numeroTramo="14">
            <distancia unidad="metros">200</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.202060</longitud>
                <latitud unidad="grados">16.449312</latitud>
                <altitud unidad="metros">440</altitud>
            </coordenadasTramoFin>
            <sector>4</sector>
        </tramo>
        <tramo numeroTramo="0">
            <distancia unidad="metros">503</distancia>
            <coordenadasTramoFin>
                <longitud unidad="grados">49.203574</longitud>
                <latitud unidad="grados">16.442826</latitud>
                <altitud unidad="metros">436</altitud>
            </coordenadasTramoFin>
            <sector>4</sector>
        </tramo>
    </tramos>
    <resultados>
        <ganador>M. Marquez</ganador>
        <tiempoGP unidad="minutos">PT40M4.628S</tiempoGP>
        <clasificacion>
            <piloto posicion="1" puntos="545">Marc Márquez</piloto>
            <piloto posicion="2" puntos="362">Álex Márquez</piloto>
            <piloto posicion="3" puntos="274">Pecco Bagnaia</piloto>
        </clasificacion>
    </resultados>
</circuito>
